### ISSUE TITLE
Forms are not styled

### ISSUE THREAD

**Issue by KhalidAbJaf** [psergicv/Restaurant-Management-System#2]
I see all forms are not styled:
http://127.0.0.1:5000/book_a_table
http://127.0.0.1:5000/contact
http://127.0.0.1:5000/book_a_table

You can try and add in some <li> tags in a unordered list or in a <table> inside some <tr> tags. After you can add some styles, so it will look better

**Comment by psergicv** [comment]
@KhalidAbJaf  - mission completed
